### PR TITLE
delete: Fail if try to delete a non-stopped container.

### LINKED ISSUE #1018: delete: cc-oci-runtime delete a running container
### What version of runtime are you using (`cc-oci-runtime version`)?
```
cc-oci-runtime version: 2.2.0
spec version: 1.0.0-rc1
commit: cfcc9cd78c2dcfeafff555e6377bb0ab293c6e77
```
### What is your host  operating system  ?
Clear Linux 

### What did you do?
1. Run a container
`docker run -ti debian bash`
2. Delete it using `cc-oci-runtime` cli
`cc-oci-runtime delete $(docker ps -ql --no-trunc)`

### What did you expect to see?
According to runc and oci-runtime spec:

*Attempting to delete a container that is not stopped MUST have no effect on the container and MUST generate an error.*

### What did you see instead?
The container was deleted and exited from docker cli
```
cc-oci-runtime delete $(docker ps -ql --no-trunc)
stopped container 395cb765e5c6e8540e2946b3e2cd263113ac498ecadf5d2be36c2732a2564251
```

*Note: Running the same with runc results in a runc fail*
```
runc delete $(docker ps -ql --no-trunc)
cannot delete container 5e5a96f08b80735a293ddf384bf96c5e0deb56e003f462378a845fad00245216 that is not stopped: running
one or more of the container deletions failed
```

### PR DESCRIPTION
**Pull request by jcvenegas**
This PR add validation in `delete` command, delete must fail if the container is not `stopped`.

Fixes #1018

### CODE REVIEW

**Comment by chavafg** [comment]
qa-passed

**Comment by chavafg** [comment]
qa-passed

File: src/oci.c [hunk 1]
```diff
@@ -1075,17 +1075,26 @@ cc_oci_stop (struct cc_oci_config *config,
 		return false;
 	}
 
+	/* if the process has finished the container is stopped */
+	if (kill (state->pid, 0) != 0) {
+		config->state.status = OCI_STATUS_STOPPED;
+	}
+
+	if (config->state.status != OCI_STATUS_STOPPED ) {
+		g_critical("cannont delete container, it is not stopped");
```
Comment (jodh-intel) [inline src/oci.c]: Typo: `cannot`

**Comment by jodh-intel** [comment]
1 minor nit, but that aside...

lgtm

**Comment by chavafg** [comment]
qa-passed

**Comment by jcvenegas** [comment]
@sameo  can you review this part, specially the part about pod_containers in 
https://github.com/01org/cc-oci-runtime/pull/1019/commits/a51537cb1d1e4d2cef2a3fa8906f5e4c6dee3f94#diff-1582f15fee5bcdb2e750609f04b951aeR1090

**Comment by jodh-intel** [comment]
@sboeuf - could you take a look?

**Comment by devimc** [comment]
lgtm

**Comment by sboeuf** [comment]
lgtm
