### PR TITLE
 mount: fix umount function

### LINKED ISSUE #325: Mounted files in /etc are zeroed out after docker cp
Started a container with cc-runtime. Verified that /etc/resolve.conf is not empty within the container and has the contents as provided in /run/docker/libcontainerd/$container_id/resolv.conf. Then copied a file from the host to the clear container

```
$ sudo docker cp ./testfile 34f30fc0b76c:/root/testfile
```

After this, the /etc/resolv.conf file inside the container is empty. Same behaviour seen for /etc/hostname and /etc/hosts.
All these files are present in the mount section of config.json and are bind mounted by the runtime.

This behaviour is not seen with runc.

### LINKED ISSUE #593: Investigate why we got :  Error response from daemon: Cannot kill container
Recently on the CI, we have got this error very frequently (almost on every execution the error appears).

```
not ok 1 HostName is passed to the container 
# (from function `clean_docker_ps' in file ../../lib//test-common.bash, line 28, 
# from function `setup' in test file network.bats, line 28) 
# `clean_docker_ps' failed with status 123 
# Error response from daemon: Cannot kill container 93606e5bd45d: Container 93606e5bd45d05718640e7747238f546534bd7b88363e05138230b240d71932c is not running 
```

### PR DESCRIPTION
**Pull request by devimc**
support for mount namespace was add in PR #577 to fix #325
all resources mounted by the runtime are part of a new
mount namespace hence when delete is called the runtime is
unable to unmount them. This patch fixes that issue joining
to the namespace and unmounting all resources

fixes #593

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

File: src/namespace.c [hunk 1]
```diff
@@ -152,7 +152,7 @@ cc_oci_str_to_ns (const char *str)
  */
 gboolean cc_oci_ns_join(struct oci_cfg_namespace *ns)
 {
-	int fd = -1;
+	int fd;
```
Comment (jcvenegas) [inline src/namespace.c]: any special reason to not initialize this fd, it is reassigned in the test lines, but if the code changes in the future would be better to initialize  it

File: src/state.c [hunk 2]
```diff
@@ -284,6 +287,37 @@ handle_state_mounts_section(GNode* node, struct handler_data* data) {
...
+	}
+	if (! (node->children && node->children->data)) {
+		g_critical("%s missing value", (char*)node->data);
+		return;
+	}
+
+	if (! g_strcmp0(node->data, "type")) {
+		n = g_new0 (struct oci_cfg_namespace, 1);
+		n->type = cc_oci_str_to_ns((char*)node->children->data);
+		data->state->namespaces = g_slist_append(data->state->namespaces, n);
```
Comment (jcvenegas) [inline src/state.c]: data is used but not does not check if is not null

File: src/state.c [hunk 3]
```diff
@@ -284,6 +287,37 @@ handle_state_mounts_section(GNode* node, struct handler_data* data) {
...
 
 /*!
+ * handler for namespaces section
+ *
+ * \param node \c GNode.
+ * \param data \ref handler_data.
+ */
+static void
+handle_state_namespaces_section(GNode* node, struct handler_data* data) {
+	struct oci_cfg_namespace* n;
```
Comment (jcvenegas) [inline src/state.c]: probably you would like to initialize with NULL

File: src/mount.c [hunk 4]
```diff
@@ -331,13 +331,15 @@ gboolean
...
 {
 	GSList  *l;
-	struct oci_cfg_namespace *ns;
-	gboolean mountns = false;
 
 	if (! config) {
 		return false;
 	}
 
+#ifndef UNIT_TESTING
```
Comment (jcvenegas) [inline src/mount.c]: why it is needed just with UNIT_TESTING?

**Comment by chavafg** [comment]
qa-failed

File: src/namespace.c (hunk 1 above)
Comment (amshinde) [inline src/namespace.c]: In any case, the above seems like a random commit.

File: src/namespace.c [hunk 5]
```diff
@@ -115,6 +144,56 @@ cc_oci_str_to_ns (const char *str)
...
+			type ? type : "", ns->path);
+		goto err;
+	}
+
+	close (fd);
+
+	/* reset to ensure any subsequent failure is
+	 * handled correctly.
+	 */
+	fd = -1;
```
Comment (amshinde) [inline src/namespace.c]: Do you need to set the fd here, since you are immediately returning after this statement.

File: src/mount.c [hunk 6]
```diff
@@ -330,11 +331,37 @@ gboolean
...
+		if (ns->type == OCI_NS_MOUNT && ns->path) {
+			mountns = cc_oci_ns_join (ns);
+			break;
+		}
+	}
+
+	/**
+	 * if there is NOT a specific mount namespace returns true
+	 * since namespace crated by unshare in \ref cc_oci_ns_setup
+	 * is destoryed when qemu ends
```
Comment (amshinde) [inline src/mount.c]: typo s/destoryed/destroyed/

File: src/mount.c (hunk 4 above)
Comment (amshinde) [inline src/mount.c]: Same question. Also, this could go in a separate commit itself.

File: src/mount.c [hunk 7]
```diff
@@ -330,11 +331,37 @@ gboolean
...
+
+		if (ns->type == OCI_NS_MOUNT && ns->path) {
+			mountns = cc_oci_ns_join (ns);
+			break;
+		}
+	}
+
+	/**
+	 * if there is NOT a specific mount namespace returns true
+	 * since namespace crated by unshare in \ref cc_oci_ns_setup
```
Comment (sameo) [inline src/mount.c]: s/crated/created/

File: src/mount.c [hunk 8]
```diff
@@ -330,11 +331,37 @@ gboolean
...
+		ns = (struct oci_cfg_namespace *)l->data;
+
+		if (ns->type == OCI_NS_MOUNT && ns->path) {
+			mountns = cc_oci_ns_join (ns);
+			break;
+		}
+	}
+
+	/**
+	 * if there is NOT a specific mount namespace returns true
```
Comment (sameo) [inline src/mount.c]: s/returns/return/

File: src/state.c (hunk 2 above)
Comment (devimc) [inline src/state.c]: according to documentation https://developer.gnome.org/glib/2.26/glib-Singly-Linked-Lists.html#g-slist-append

```
g_slist_append ()
Returns : the new start of the GSList
```

File: src/state.c (hunk 3 above)
Comment (devimc) [inline src/state.c]: is not needed

File: src/mount.c (hunk 4 above)
Comment (devimc) [inline src/mount.c]: I have to remove this line and fix mount test

File: src/mount.c [hunk 9]
```diff
@@ -335,6 +336,35 @@ cc_oci_handle_unmounts (const struct cc_oci_config *config)
 		return false;
 	}
 
+#ifndef UNIT_TESTING
+	struct oci_cfg_namespace *ns;
+	gboolean mountns = false;
+
+	/**At this point qemu is not running if there is
```
Comment (devimc) [inline src/mount.c]: nice catch

File: src/mount.c (hunk 6 above)
Comment (devimc) [inline src/mount.c]: nice catch

File: src/namespace.c (hunk 5 above)
Comment (devimc) [inline src/namespace.c]: nice catch

File: src/mount.c [hunk 10]
```diff
@@ -335,6 +336,35 @@ cc_oci_handle_unmounts (const struct cc_oci_config *config)
...
+	 * a mount namespace with a path we have join to
```
Comment (devimc) [inline src/mount.c]: nice catch

File: src/namespace.c [hunk 11]
```diff
@@ -115,6 +144,56 @@ cc_oci_str_to_ns (const char *str)
...
+	int saved;
+	const gchar *type;
+
+	type = cc_oci_ns_to_str (ns->type);
+
+	fd = open (ns->path, O_RDONLY);
+
+	if (fd < 0) {
+		saved = errno;
+		g_critical ("failed to open %s", ns->path);
```
Comment (devimc) [inline src/namespace.c]: agree

File: src/namespace.c [hunk 12]
```diff
@@ -115,6 +144,56 @@ cc_oci_str_to_ns (const char *str)
 }
 
 /**
+ * Join to a specific namespace
```
Comment (devimc) [inline src/namespace.c]: enough,  going back to English classes  x_x

File: src/state.c (hunk 2 above)
Comment (jcvenegas) [inline src/state.c]: Sorry, I mean the "struct handler_data* data" parameter is not checked but you access to its members

Comment (devimc) [inline src/state.c]: ohhh ok, fixing...

File: src/namespace.c (hunk 1 above)
Comment (devimc) [inline src/namespace.c]: 1. cc_oci_ns_join is a new function
2. cppcheck reports errors if fd is initialized here
3. fd is initialized below

**Comment by jcvenegas** [comment]
lgtm

**Comment by sameo** [comment]
LGTM
