### PR TITLE
runtime: Fix docker file descriptor leaks

### LINKED ISSUE #616: Docker is leaking file descriptors
It seems as though docker-containerd and docker-containerd-shim are leaking file descriptors.
I ran a 4K repetition loop that starts and stops 10 concurrent containers, and docker failed to continue launching more containers at iteration 3276.

**Steps to reproduce the issue:**

1. To reproduce this issue, I ran the following script to a reasonable number of iterations i.e. 4000

```
REPS=4000
MAX_CONTAINERS=10

docker_run()
{
  local ITER=$1
  echo -e "\nIteration $ITER"
  for i in $(seq 1 $MAX_CONTAINERS); do
        docker run -d clearlinux
        bash -c "while true; do sleep 1; done"
  done
}

docker_stop()
{
        docker stop $(docker ps -qa)
        docker rm -f $(docker ps -qa)
}

run_test()
{
for j in $(seq 1 $REPS); do
        docker_run $j
        sleep 2
        docker ps -a
        docker_stop
done
}
run_test
```

2. Count how many file descriptors are open in each iteration for the processes: qemu-lite-system-x86_64, dockerd, dockerd-containerd and docker-containerd-shim:

`lsof -n -p $(echo $(pidof  "${PID}") | awk '{$1=$1}1' OFS=" -p ") | wc -l"`

3. The count of file descriptors increased with the number of iterations as is shown in the following charts:

docker-containerd
docker-containerd-shim

4. Docker hangs after iteration 3275 once the number of docker-containerd opened files was: 65535
```
# lsof -n -p $(pidof docker-containerd) | wc -l
655535

```
5. max open files for docker-containerd process
```
cat /proc/$(pidof docker-containerd)/limits | grep "Max open files"
Max open files            65536
```

The complete data collection with count of file descriptors for the processes listed in 3 is below:

[output_23012017_0036_csv.txt](https://github.com/01org/cc-oci-runtime/files/725252/output_23012017_0036_csv.txt)

6. docker info:
```
Containers: 7
 Running: 5
 Paused: 0
 Stopped: 2
Images: 1
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: cor runc
Default Runtime: cor
Security Options:
Kernel Version: 4.9.5-294.native
Operating System: Clear Linux Software for Intel Architecture
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.63 GiB
Name: clrContainersDev
ID: 3FHD:CE6K:AEUC:WLZS:RSSE:MEZU:2LSP:GODG:BSCC:XMA6:Q4SB:SSAN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 50
 Goroutines: 52
 System Time: 2017-01-23T17:32:04.880737686Z
 EventsListeners: 0
```

### PR DESCRIPTION
**Pull request by devimc**
Docker provides a cgroup path where the workload MUST be
added before create pid file otherwise docker will create a new
cgroup and add the workload to it.
When workload process ends the runtime MUST delete the cgroup path
notifying docker to free its open event file descriptors otherwise
docker won't close them causing file descriptors leaks.

fixes #616

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

File: src/command.c [hunk 1]
```diff
@@ -153,6 +154,7 @@ handle_command_stop (const struct subcommand *sub,
 	gchar             *config_file = NULL;
 	gboolean           ret;
 	GNode*             root = NULL;
+	gchar             *cgroup_dir;
```
Comment (jodh-intel) [inline src/command.c]: Needs to be set to `NULL` for the `g_free_if_set()` call.

File: src/oci.h [hunk 2]
```diff
@@ -109,6 +109,9 @@
 /** Mode for \ref CC_OCI_WORKLOAD_FILE. */
 #define CC_OCI_SCRIPT_MODE		0755
 
+/** Mode for cgroup directory. */
+#define CC_OCI_CGROUP_MODE		0755
```
Comment (jodh-intel) [inline src/oci.h]: Does it have to be `0755`? If not, can we use `CC_OCI_DIR_MODE`?

File: src/command.c (hunk 1 above)
Comment (jodh-intel) [inline src/command.c]: Ah - I see that it can't actually be `NULL` now, so this change isn't actually required (but might be good anyway from a maintenance perspective in case the code changes later).

File: src/command.c [hunk 3]
```diff
@@ -207,6 +209,13 @@ handle_command_stop (const struct subcommand *sub,
 	g_print ("stopped container %s\n", config->optarg_container_id);
 
 out:
+	cgroup_dir = g_strdup_printf ("/sys/fs/cgroup/memory/%s",
```
Comment (jcvenegas) [inline src/command.c]: if (config->oci.oci_linux.cgroupsPath) ?

File: src/process.c [hunk 4]
```diff
@@ -1186,6 +1193,33 @@ cc_oci_vm_launch (struct cc_oci_config *config)
...
 
+	/* Before create pid file!
+	 *
+	 * Docker provides a cgroup path that MUST be created before pid file
+	 * workload pid MUST be copy to task and cgroup.procs notifying to docker
+	 * that the workload is part of a cgroup.
+	 * With this change docker WILL NOT create a new cgroup and WILL NOT copy
+	 * the workload pid to this new cgroup avoiding file descriptor leaks
+	 */
+	cgroup_dir = g_strdup_printf ("/sys/fs/cgroup/memory/%s",
```
Comment (jcvenegas) [inline src/process.c]: check if cgroupsPath is not null

File: src/process.c [hunk 5]
```diff
@@ -788,6 +788,13 @@ cc_oci_vm_launch (struct cc_oci_config *config)
 	GSocketConnection *shim_socket_connection = NULL;
 	GError            *error = NULL;
 	int                status = 0;
+	char               buf[64] = { 0 };
```
Comment (jcvenegas) [inline src/process.c]: why this magic number?

File: src/process.c [hunk 6]
```diff
@@ -1186,6 +1193,33 @@ cc_oci_vm_launch (struct cc_oci_config *config)
...
+	cgroup_dir = g_strdup_printf ("/sys/fs/cgroup/memory/%s",
+		config->oci.oci_linux.cgroupsPath);
+	g_mkdir_with_parents (cgroup_dir, CC_OCI_CGROUP_MODE);
+
+	buf_len = g_snprintf (buf, sizeof(buf), "%d", config->state.workload_pid);
+
+	cgroup_tasks = g_strdup_printf ("%s/tasks", cgroup_dir);
+	fd_tasks = open (cgroup_tasks, O_WRONLY);
+	if (write (fd_tasks, buf, (size_t)buf_len) <= 0) {
+		g_critical ("failed to copy workload pid to cgroup tasks");
```
Comment (jodh-intel) [inline src/process.c]: I'd personally check the return from `open` but if that fails the `write` will detect it. However, I'd add a call to `strerror(errno)`.

File: src/process.c [hunk 7]
```diff
@@ -1186,6 +1193,33 @@ cc_oci_vm_launch (struct cc_oci_config *config)
...
+		goto out;
+	}
+
+	cgroup_procs = g_strdup_printf ("%s/cgroup.procs", cgroup_dir);
+	fd_procs = open (cgroup_procs, O_WRONLY);
+	if (write (fd_procs, buf, (size_t)buf_len) <= 0) {
```
Comment (jodh-intel) [inline src/process.c]: Same comment as above.

File: src/process.c [hunk 8]
```diff
@@ -1186,6 +1193,33 @@ cc_oci_vm_launch (struct cc_oci_config *config)
...
+		g_critical ("failed to copy workload pid to cgroup procs");
```
Comment (jodh-intel) [inline src/process.c]: Same comment as above.

File: src/command.c (hunk 3 above)
Comment (jodh-intel) [inline src/command.c]: There are two occurrences of `"/sys/fs/cgroup/memory/%s"` so might be worth a macro for the static bit (or all of it), or even an macro / inline function for this.

File: src/process.c (hunk 5 above)
Comment (jodh-intel) [inline src/process.c]: Why `64`?

File: src/process.c [hunk 9]
```diff
@@ -1186,6 +1193,33 @@ cc_oci_vm_launch (struct cc_oci_config *config)
...
+	 * workload pid MUST be copy to task and cgroup.procs notifying to docker
+	 * that the workload is part of a cgroup.
+	 * With this change docker WILL NOT create a new cgroup and WILL NOT copy
+	 * the workload pid to this new cgroup avoiding file descriptor leaks
+	 */
+	cgroup_dir = g_strdup_printf ("/sys/fs/cgroup/memory/%s",
+		config->oci.oci_linux.cgroupsPath);
+	g_mkdir_with_parents (cgroup_dir, CC_OCI_CGROUP_MODE);
+
+	buf_len = g_snprintf (buf, sizeof(buf), "%d", config->state.workload_pid);
```
Comment (jodh-intel) [inline src/process.c]: Would `g_strdup_printf()` be easier to use here?

File: src/oci.h (hunk 2 above)
Comment (devimc) [inline src/oci.h]: it have to be 0755

File: src/spec_handlers/linux.c [hunk 10]
```diff
@@ -102,6 +102,8 @@ handle_linux_section (GNode *root, struct cc_oci_config *config)
 		g_node_children_foreach(root, G_TRAVERSE_ALL,
 			(GNodeForeachFunc)handle_namespaces_section,
 			config);
+	} else if (! g_strcmp0 (root->data, "cgroupsPath")) {
+		config->oci.oci_linux.cgroupsPath = g_strdup (root->children->data);
```
Comment (jodh-intel) [inline src/spec_handlers/linux.c]: Could you add any new tests for this change (for example to `tests/spec_handlers/linux_test.c`)?

**Comment by chavafg** [comment]
qa-passed

File: src/oci.h (hunk 2 above)
Comment (jodh-intel) [inline src/oci.h]: OK, in which case, I'd add a comment in the code explaining that's why you can't use `CC_OCI_DIR_MODE` (otherwise, someone might come along later and -- trying to be helpful -- "fix" this assuming it's a valid change to make ;-).

File: src/command.c (hunk 3 above)
Comment (devimc) [inline src/command.c]: good catch!
thanks

File: src/spec_handlers/linux.c (hunk 10 above)
Comment (devimc) [inline src/spec_handlers/linux.c]: sure

**Comment by jodh-intel** [comment]
kudos for tracking this fixing this btw! :smile:

File: src/oci.h (hunk 2 above)
Comment (devimc) [inline src/oci.h]: ok, thanks

File: src/process.c (hunk 5 above)
Comment (devimc) [inline src/process.c]: using g_strdup_printf

File: src/process.c (hunk 8 above)
Comment (devimc) [inline src/process.c]: good catch,
thanks

**Comment by devimc** [comment]
@jodh-intel  @jcvenegas thanks for your review

**Comment by sboeuf** [comment]
@devimc Nice fix :)

1. Could you slightly change your commit message with something like that:
"Docker provides a cgroup path, and it expects related files to be filled with the proper PID. In case corresponding files are not filled as expected, it does it by itself, leading to file descriptors leaks.
In order to comply with Docker workflow and to make sure it does not try to fill those files by itself, we MUST create them before the PID workload file. PID MUST be copied to task and cgroup.procs files so as to notify to Docker that the workload is part of the expected cgroup."

2. Maybe a dumb question but where does the leak comes from exactly ? I mean, if we don't create those files for the specified cgroup, you say that Docker will create them, but where is the root issue ? Because I expect Docker to properly close the file descriptor he created, right ?

**Comment by devimc** [comment]
@sboeuf 
1. sure, I can improve commit message
2. Docker creates a new cgroup (/sys/fs/cgroup/memory/xxxx) and adds the workload process to it
when the workload ends docker expects that runtime deletes these files, but we do not know where they are, for this reason docker keeps they open

**Comment by sboeuf** [comment]
@devimc Thanks for the explanation. You say we don't know where those files are, but don't you think we can find them from the cgroup path provided by Docker ?
I ask because it would allow us to avoid the creation of those files, only the removal at the end.

**Comment by devimc** [comment]
@sboeuf before this patch, docker created a new cgroup because we did not use the path provided by it,
we did not know where this new cgroup was created hence we cannot notify docker to free its open fds

**Comment by sboeuf** [comment]
Ah okay, it relies on a different one in case we don't use the one provided....
Thanks

**Comment by jcvenegas** [comment]
lgtm

File: src/process.c [hunk 11]
```diff
@@ -1186,6 +1192,38 @@ cc_oci_vm_launch (struct cc_oci_config *config)
 	 */
 	ret = cc_proxy_disconnect (config->proxy);
 
+	/* Before create pid file!
+	 *
+	 * Docker provides a cgroup path that MUST be created before pid file
+	 * workload pid MUST be copy to task and cgroup.procs notifying to docker
```
Comment (amshinde) [inline src/process.c]: s/copy/copied/

Comment (devimc) [inline src/process.c]: good catch!  thanks

**Comment by amshinde** [comment]
lgtm.
Nice fix Julio!
