### PR TITLE
proxy: Simplify fd passing and the message read loop

### LINKED ISSUE #508: 2.1 - docker: Error response from daemon: shim error: open pid: no such file or directory.
When running `make docker-tests`, I see some tests failing with this error:

```
2.1 - docker: Error response from daemon: shim error: open pid: no such file or directory.
```

It happens "from time to time" but is fairly reproducible: once every few runs of `make docker-tests`. It smells like our writing of the pid file could be racy, somehow? or we simply fail at writing it.

### PR DESCRIPTION
**Pull request by sameo**
When passing the OOB fd data, we pass the dummy data ('F') and
that simplifies the message reading loop:

- When receiving a message, we no longer need to read the OOB data
  at any point in time, but only at first.

- We only need to read actual data in the read loop, and there we
  can handle EAGAIN more robustly: We retry as long as we don't
  get the whole message length.

Fixes #508

Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>

### CODE REVIEW

File: src/proxy.c [hunk 1]
```diff
@@ -257,14 +256,15 @@ cc_proxy_msg_read (GIOChannel *source, GIOCondition condition,
 
 	/* read length */
 	bytes_read = recvmsg(proxy_data->socket_fd, &msg, 0);
+	total_bytes_read += bytes_read;
```
Comment (jodh-intel) [inline src/proxy.c]: This will make `total_bytes_read` negative if `recvmsg(2)` fails.

**Comment by chavafg** [comment]
qa-failed

File: src/proxy.c (hunk 1 above)
Comment (sameo) [inline src/proxy.c]: Yep, and I need to fix a proxy unit test as well.

**Comment by sameo** [comment]
@chavafg Fixed the unit tests failures, could you please re-run the tests ?

**Comment by GabyCT** [comment]
@sameo I am re-running again the tests :)

**Comment by sameo** [comment]
thanks @GabyCT !

File: proxy/api/client.go [hunk 2]
```diff
@@ -64,6 +64,37 @@ func (client *Client) sendPayload(id string, payload interface{}) (*Response, er
...
+	}
+
+	if err := WriteMessage(client.conn, &req); err != nil {
+		return nil, nil, err
+	}
+
+	// I/O fd
+	newFd, err := ReadFd(client.conn)
+	if err != nil {
+		return nil, nil, errors.New("sendPayloadGetFd: couldn't read fd")
```
Comment (jodh-intel) [inline proxy/api/client.go]: I wonder if it's worth adding the `id` to this error message?

File: src/proxy.c [hunk 3]
```diff
@@ -277,14 +279,14 @@ cc_proxy_msg_read (GIOChannel *source, GIOCondition condition,
...
 					*proxy_data->oob_fd);
-				fd_read = true;
 			}
 		}
 	}
 
 	/* only out-of-band data was received */
 	if (bytes_read < sizeof (buf_len) || iov_buffer[0] == 'F' ) {
-		goto out1;
+		proxy_data->oob_fd_found = true;
```
Comment (devimc) [inline src/proxy.c]: I think that you should move this to line 280

File: src/proxy.c [hunk 4]
```diff
@@ -264,11 +264,13 @@ cc_proxy_msg_read (GIOChannel *source, GIOCondition condition,
...
 	if (bytes_read == 0) {
-		g_critical("failed to read lenght");
+		g_critical("failed to read length");
 		return false;
 	}
 
-	if (proxy_data->oob_fd) {
+	total_bytes_read += bytes_read;
+
+	if (proxy_data->oob_fd && !proxy_data->oob_fd_found) {
```
Comment (devimc) [inline src/proxy.c]: ```!proxy_data->oob_fd_found``` is not needed because at this point it always will be true

File: src/proxy.c [hunk 5]
```diff
@@ -47,6 +47,7 @@ struct watcher_proxy_data
 	 * otherwise it WILL wait
 	 */
 	int         *oob_fd;
+	gboolean    oob_fd_found;
```
Comment (devimc) [inline src/proxy.c]: you could remove this field and create a local variable in cc_proxy_msg_read since this variable is only used by this function

File: src/proxy.c (hunk 4 above)
Comment (sameo) [inline src/proxy.c]: It will be false in the first round.

File: src/proxy.c (hunk 5 above)
Comment (sameo) [inline src/proxy.c]: Yes, but I need to carry it through 2 `cc_proxy_msg_read()` calls. Once we find the OOB data, we return from this routine and get called again when the actual data comes in. On the second run we want to skip the OOB check.

File: src/proxy.c (hunk 3 above)
Comment (devimc) [inline src/proxy.c]: ```oob_fd_found``` will change to true when **only** out-of-band data is read
I think that this is not equivalent , ```oob_fd_found``` have to change when the fd is copied

File: src/proxy.c (hunk 5 above)
Comment (jodh-intel) [inline src/proxy.c]: Sounds like we might benefit from a `g_debug()` call or two?

**Comment by sameo** [comment]
@GabyCT How did the tests go ?

File: src/proxy.c (hunk 5 above)
Comment (sameo) [inline src/proxy.c]: We do 2 reads for the 2 separate messages that the proxy send us on its blocking socket. So at first we read the OOB ancillary data and the fd, and then get the 2nd message for reading the actual message. I changed the code slightly to make that clearer, with even code comments :)

File: src/proxy.h [hunk 6]
```diff
@@ -28,6 +28,14 @@
 /* allocate 2 streams, stdio and stderr */
 #define IO_STREAMS_NUMBER 2
 
+/*
+ * 4 bytes for the message length.
+ * 4 bytes for the message flags.
+ */
+#define HEADER_MESSAGE_LENGTH 4
+#define HEADER_MESSAGE_FLAGS  4
+#define MESSAGE_HEADER_LENGTH 8
```
Comment (jodh-intel) [inline src/proxy.h]: `#define MESSAGE_HEADER_LENGTH (HEADER_MESSAGE_LENGTH+HEADER_MESSAGE_FLAGS)` ?

File: proxy/api/client.go [hunk 7]
```diff
@@ -64,6 +65,37 @@ func (client *Client) sendPayload(id string, payload interface{}) (*Response, er
 	return &resp, nil
 }
 
+func (client *Client) sendPayloadGetFd(id string, payload interface{}) (*Response, *os.File, error) {
```
Comment (jodh-intel) [inline proxy/api/client.go]: I think it would be worth a comment on this function since although the name is fairly descriptive, there are 3 operations going on here (send payload, read fd, read message), but the name suggests 2.

File: src/proxy.c [hunk 8]
```diff
@@ -264,88 +280,81 @@ cc_proxy_msg_read (GIOChannel *source, GIOCondition condition,
...
+			g_critical("could not read the control message");
+			goto out;
 		}
-	}
 
-	/* only out-of-band data was received */
-	if (bytes_read < sizeof (buf_len) || iov_buffer[0] == 'F' ) {
-		goto out1;
+		data = CMSG_DATA(cmsg);
+		if (! (data && iov_buffer[0] == 'F')) {
```
Comment (jodh-intel) [inline src/proxy.c]: This "magic `F`" is important. But it's also mentioned explicitly in various places (4 times). From a maintenance perspective, I'd be inclined to create a `#define` for it and change all hard-coded references to use the define (including all the references in comments). This would bring `proxy.c` sort of in line with `proxy.go` which defines `fileFlag` (although `proxy.go` could do a bit better in this respect too as there are various mentions of "`F`" scattered about in comments).

**Comment by jodh-intel** [comment]
lgtm

**Comment by sameo** [comment]
@GabyCT Could we please run our QA tests on this PR ?

**Comment by sameo** [comment]
@devimc Please give it another review round.

**Comment by GabyCT** [comment]
@sameo I checked the test results and I saw that the failures that we have in docker integration tests and make distcheck are related with the issue https://github.com/01org/cc-oci-runtime/issues/535 as all the errors happen using exec (Error response from daemon: rpc error: code = 2 desc = containerd: container not started docker integration)

**Comment by sboeuf** [comment]
lgtm
