### PR TITLE
mount: fix cppcheck error, close fd

### LINKED ISSUE #205: cppcheck fails in Clear Linux
make cppcheck in Clear Linux fails 

[src/mount.c:166]: (error) Return value of allocation function 'creat' is not stored.
Version:
cppcheck --version
Cppcheck 1.75

### PR DESCRIPTION
**Pull request by jcvenegas**
Fixes #205

Fix cppcheck :  Return value of allocation function 'creat' is not stored .
Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

File: src/mount.c [hunk 1]
```diff
@@ -163,12 +163,17 @@ cc_oci_perform_mount (const struct cc_oci_mount *m, gboolean dry_run)
...
 
 	if (S_ISREG(st.st_mode)) {
-		if(creat (m->dest, st.st_mode) < 0 ) {
+		int fd;
+		fd = creat (m->dest, st.st_mode);
+		if( fd < 0 ) {
 			g_critical ("Unable to handle mount file:"
 					"creating file %s (%s)",
 					m->dest, strerror (errno));
+			close(fd);
```
Comment (amshinde) [inline src/mount.c]: You dont need to call close if creat fails

Comment (jcvenegas) [inline src/mount.c]: right!,  fixed :)

**Comment by amshinde** [comment]
lgtm

**Comment by jodh-intel** [comment]
I re-spun the Travis build (as it looks like the gcc build got hit by the random #155 issue) and it is now passing, hence:

lgtm.
